### ISSUE TITLE
Fences/Panes/Iron Bars render incorrectly in 1.4.3-a2

### ISSUE THREAD

**Issue by chland** [chunky-dev/chunky#434] opened 2017-07-06 12:32 UTC
It looks like 1.4.3-alpha2 broke the rendering of fences, iron bars and glass panes. They always render as if they were completly surrounded by blocks (connections at all 4 sides).

![fence_bug](https://user-images.githubusercontent.com/472894/27910946-9cad94ce-6257-11e7-800b-84e5992fa55a.jpg)

**Comment by llbit** [comment] 2017-07-07 07:17
That looks like a nice test map! Could you share it please?

This error is caused by the AIR block being treated as a solid block after [this commit](a582f0293f92e0fd947d955d3fa89c1f52276d5f).

The change that broke this is where I moved all default material property initialization out of the block objects. I wrote a script to do the rewrite, and it missed the AIR block because it was the only block not in the block array. I have moved the AIR properties back into the block object because that should not be changed anyway.

**Comment by chland** [comment] 2017-07-07 08:28
Regarding the map: thats basically just a copy of the Mineways Test-map :) 

[blocktest.zip](https://github.com/llbit/chunky/files/1130418/blocktest.zip)

**Comment by chland** [comment] 2017-07-07 10:45
I just wanted to add, that this is still an issue in a3 but I guess https://github.com/llbit/chunky/commit/5ab2f96a299906dddfe2fcdd3578bd0d4dee37a1 fixes the problem !?

**Comment by llbit** [comment] 2017-07-07 12:22
@chland yes, I made a silly mistake there which was fixed in alpha4.

**Comment by llbit** [comment] 2017-07-07 12:22
@chland Thanks for the map. I've seen screenshots of it sometimes before but never knew where it was from. Seems quite useful!

**Comment by chland** [comment] 2017-07-07 17:23
I've got good news........and bad news. Its fixed for air-blocks but i then noticed, that some of the fences i saw were connecting to a nearby wheat-field. so i did some tests and it looks like fences, iron-bars (and I guess panes - haven't tested them) are connecting to hoppers, sugar-cane, all crops, etc. - and iron-bars connecting to fences is wrong, too :)

And why the hell do Iron Bars connect to Melons and Pumpkins in Minecraft? Never noticed that... strange. But anyways... here are 2 screenshots:

Chunky:

![fences_bug_2](https://user-images.githubusercontent.com/472894/27968565-cd1abfe2-6347-11e7-8f05-1a953f856e5c.jpg)

Minecraft:

![fences_bug_mc](https://user-images.githubusercontent.com/472894/27968838-f2b07f66-6348-11e7-9e15-204a8a416560.jpg)

Btw. I don't know if this is something you can easily do but it could probably be a nice feature if the new "Fences/Panes connect to Stairs"-mechanic Mojang added in 1.12 could be toggled on and off. At least in older builds, a lot of people used the fact that glass didn't connect to stairs to create open doors.

**Comment by llbit** [comment] 2017-07-07 20:12
This is the place where Chunky tests if a fence connects to another block: [Block.java:2927](https://github.com/llbit/chunky/blob/master/chunky/src/java/se/llbit/chunky/world/Block.java#L2927). I don't know if it has ever been fully correct, because I never really tested it extensively. On the other hand we got now bug reports about it before. It would be great to update it so that it better matches the Minecraft behavior.

**Comment by chland** [comment] 2017-07-07 20:58
I created a better test-scene and now its getting really "interesting" :) Your changes seem to have caused a few other interesting differences.

![minecraft](https://user-images.githubusercontent.com/472894/27976399-a872c080-6366-11e7-85d1-f8912c1a1237.jpg)

1.4.2 rendered pretty much the same way as Minecraft does:

![fence_test-142](https://user-images.githubusercontent.com/472894/27976402-ab2bad1e-6366-11e7-980c-db9e163651d2.jpg)

- Fences/Panes/Bars didn't connect to stairs, which is correct for MC < 1.12
- Fences/Panes/Bars did connect to pumkins and meloons which is correct for < 1.12

The only real "bug" i can see are the single lava/water-blocks that aren't rendered as full blocks.
 
![fence_test-143](https://user-images.githubusercontent.com/472894/27976409-aef1a930-6366-11e7-93a3-f1b5fcbe9532.jpg)

Yeah... looks like fences, bars and panes are a little bit too eager to connect to stuff.

Hope this helps... unfortunatly my Java skills are pretty much non existent.

**Comment by llbit** [comment] 2017-07-09 20:53
I found an error in the automated refactoring script that caused the previous problem with the AIR block. The isSolid property was incorrectly renamed due to a copy-paste error.

The issue with the water is caused by the fences and glass panes not being treated as solid blocks. I think they can be tagged as solid blocks to fix that without breaking anything else.

**Comment by chland** [comment] 2017-07-12 20:18
Just a quick update: Alpha 5 is rendering like 1.4.2 again :) You're awesome ;)

Only thing left regarding that topic is the question if you wanna make Chunky render like 1.12 (no connections to pumpkins/melons but connections to stairs) or keep the "old" logic.

**Comment by llbit** [comment] 2017-07-12 23:47
Thank you :) Yes, I am planning to fix the connectors so they behave like in Minecraft. Not sure if I want to go through and test all block combinations.

**Comment by llbit** [comment] 2017-07-14 09:45
I think I got everything right for this test scene in snapshot 1.4.3-beta1.

**Comment by chland** [comment] 2017-07-14 13:35
I guess you're going to hate me... but... nope, its not rendering correctly.

Top is MC 1.12, bottom is beta 1:

![fences_beta](https://user-images.githubusercontent.com/472894/28213804-f6704352-68a7-11e7-9e44-8437377792a9.jpg)

- Nether-Brick Fences shouldn't connect to regular Fences
- Glass-Panes should connect to Iron-Bars
- Glass-Panes should not connect to Fences

After seeing these bugs i did some more tests:

![fence_bugs](https://user-images.githubusercontent.com/472894/28214240-bfaf7c28-68a9-11e7-81d9-af83b2fe509a.jpg)

- Fences shouldn't connect to Glass-Blocks
- Iron Bars should not connect to Fence-Gates
- Fences should only connect to the sides of Fence Gates

**Comment by llbit** [comment] 2017-07-16 10:24
Thanks! That's a lot of combinations I didn't think about! It should be fairly easy to fix all those combinations.

**Comment by chland** [comment] 2017-07-17 09:46
I really wish i could write "Yay, everything is fine!!!" ... but i can't :-(

Why most of the mentioned issues are fixed, some things are still off:

![fence_glass](https://user-images.githubusercontent.com/472894/28262742-7532756e-6ae4-11e7-8cbc-983309c894e0.jpg)

- the fences should not connect to the glass panes

And unfortunatly, I remembered that there are cobblestone-walls in the game... and so i edited the test-scene again and tried some things:

![more_fence_bugs](https://user-images.githubusercontent.com/472894/28262733-6c238aee-6ae4-11e7-9800-fb808b06d911.jpg)

The bug that cobblestone walls connect to leaf-blocks exists for iron bars and glass panes, too (right now, they ARE connecting, but they should NOT).

Sorry for finding this stuff only one bug after another instead of giving you one huge list of things that are broken but i'm not that much of a minecraft-builder and don't know all those strange "what connects to what"-rules and only test stuff that comes to my mind when i see other stuff (for example i just remembered that leaves aren't connecting after seeing a video by BDoubleO where he is meesing around with leaves).

**Comment by llbit** [comment] 2017-07-17 10:34
@chland Thanks! I appreciate that you report these discrepancies, because I'm lazy and haven't checked them myself :)

**Comment by llbit** [comment] 2017-07-19 21:19
I have done more testing on these issues. The stairs should only connect to fences, walls, panes, and bars if the stair block is facing away from the fence-like block. I fixed many issues but not sure I got all of them. Please update this if you find any more issues. I will publish a new snapshot soon.

**Comment by chland** [comment] 2017-07-20 11:34
Just a quick update: as far as i can see, my current test-scene now renders the same way as it is rendered in MC 1.12 - i will test some other things later today and let you know if I found anything strange :-)

**Comment by chland** [comment] 2017-07-20 13:56
I did some more tests. Lets start by saying that i already know that some of the following things "work as intended" (Banners, Armor Stands, etc. not rendering). This is just a list of everything I noticed in my test-scene:

* Dragon Heads are rendered as player-heads (i guess adding them would be a problem as they are bigger than 1 block?)
* Flowers in Flower Pots aren't rendered
* Armor Stands, Boats, Minecarts, Paintings, Banners, etc. are missing
* (Mossy) Cobblestone Walls connect to glass-blocks but should NOT
* (Mossy) Cobblestone Walls do NOT "connect" to normal solid blocks placed on top of them (they should change the same way they do when you place a torch on them)
* (Mossy) Cobblestone Walls do NOT "connect" to End Rods, Trapdoors, Glass blocks/panes  placed on top of them (same bug as above)
* Speaking of walls: in Minecraft they DO show connections if liquids flow on top of them (And NO, I do NOT understand why they choose to do that)

Everything else looked pretty good.

**Comment by llbit** [comment] 2017-07-21 18:38
Thank you for the new list! I have fixed a few of the issues regarding (mossy) stone walls. Paintings should be rendered, no idea why they are not being rendered. I'll investigate that.

The flower pots, dragon heads, armor stands, boats, banners, minecarts etc. are not supported yet. That will come in a future release.

Right now I'd like to finish up the 1.4.3 release, so I will focus mainly on regressions.

It's nice to have a good list of all the things Chunky should support but does not render correctly for future work.

**Comment by llbit** [comment] 2017-07-21 18:43
The paintings issue seems to have been caused by Mojang deciding to change the painting entity ID from "Painting" to "minecraft:painting" in Minecraft 1.12.

**Comment by chland** [comment] 2017-07-22 13:50
Walls are still a bit wonky, Paintings are OK now :)

![beta4-bugs](https://user-images.githubusercontent.com/472894/28491666-666507d0-6ef5-11e7-8f54-58fd118d9990.jpg)

**Comment by chland** [comment] 2017-08-21 09:45
I should really stop messing around with walls, fences, etc. :-(

I found some more "bugs";

![cobblewalls_bugs](https://user-images.githubusercontent.com/472894/29513151-b80b3164-8664-11e7-955c-571750167591.jpg)

Looks like  Minecraft does strange things to gates when they are placed near cobble-walls.

**Comment by llbit** [comment] 2017-08-21 10:12
Ah, cool. That is simple to fix. I just have to change the condition for the fence gate height to be lowered if there is at least one stone wall adjacent.

**Closed** 2022-08-31 11:33 UTC
Labels: bug, renderer
