### ISSUE TITLE
[2.2] Changing Target SPP doesn't update actual Target SPP

### ISSUE THREAD

**Issue by StanleyMines** [chunky-dev/chunky#695] opened 2020-10-03 05:08 UTC
Changing the textbox for Target SPP does not update the actual value used to end the render or display the progress bar.
Changing from 10 -> 1000 (at like 5), and it counts to 10, saves and stops (reaching the end of the progress bar).

**Comment by StanleyMines** [comment] 2020-10-03 05:09
To force it to update, changing the dump interval seems to work fairly well. Doesn't always update if other settings are updated.

**Comment by leMaik** [comment] 2020-10-03 11:41
Can't reproduce.

**Comment by jackjt8** [comment] 2020-10-03 13:43
This issue tends to be related to the denoiser plugin rather than Chunky itself.

**Comment by leMaik** [comment] 2021-01-28 18:57
This is something that needs to be addressed by the plugin.

**Closed by leMaik** 2021-01-28 18:57 UTC
