### ISSUE TITLE
feature request: allow the sky to render dawn/dusk with negative altitude for the sun angle

### ISSUE THREAD

**Issue by Delvin4519** [chunky-dev/chunky#1086] opened 2021-12-08 03:14 UTC
Title is pretty self explanatory.

Right now the sky renders up to the sun angle of 0 degrees, even though a negative sun angle can be entered. It should be possible for the sky to render twilight/dawn/dusk/daybreak/nightfall when the sun angle is between 0 and -18 degrees.

**Comment by leMaik** [comment] 2021-12-08 06:33
This is duplicate of #497, which you created a few years ago. We haven't forgotten about this. ;-)

**Closed by leMaik** 2021-12-08 06:33 UTC

**Comment by Peregrine05** [comment] 2021-12-08 11:18
That is what happens with the Preetham sky simulation. If you use Nishita sky simulation, then the sky renders properly with the sun below the horizon.
