### ISSUE TITLE
Occasional rendering reset

### ISSUE THREAD

**Issue by hespook** [chunky-dev/chunky#94] opened 2013-03-15 18:03 UTC
Chunky sometimes restarts the rendering without me changing any perimeters or touching the render controls.

I haven't been able to determinate the cause but it has occurred when changing tabs in render controls and when switching to Chunky from other windows.

**Comment by jackjt8** [comment] 2022-10-19 18:06
While in the past, pre-1.4.5, I can confirm that this was a semi-random occurrence for me too... I cannot say that in 1.4.5, or much rather beyond, that this was still an issue for me. I can only assume that this bug was eventually fixed.

I have not had any reports over the past two years either of this still being an issue so unless someone confirms this is still occurring I will close this issue in a few days.

**Comment by Peregrine05** [comment] 2022-12-14 10:11
Previously, opening the `Advanced` tab for the first time would cause a render reset. That issue has since been fixed. As to the render resetting when switching to the Chunky window, clicking the Chunky window to switch to it may have caused a setting to inadvertently be changed, e.g., slightly moving the camera view if the mouse is not kept perfectly still through the duration of the click.

**Closed by Peregrine05** 2022-12-14 10:11 UTC
Labels: bug
