### ISSUE TITLE
Y min/max clip (re)loading inconsistencies

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1175] opened 2022-02-23 22:37 UTC
Affected versions - `2.5.0-51-gad88ccd7`,  `2.4.2-21-g1304a5fe`, `2.4.2`, `2.5.0-SNAPSHOT.75.g8bd287901`
Unaffected versions - `2.5.0-15-g1ba5d5b`
Exported region from a World Painter world - [Kingdom of Galekin_bug.zip](https://github.com/chunky-dev/chunky/files/8128264/Kingdom.of.Galekin_bug.zip)

Steps to reproduce:

1. Select a 1.18 world with terrain that is above Y 256.
2. Set `Y min clip` to -64 and `Y max clip` to 320.
3. Look for anomalies in `Map View`  and select them; such as:
![image](https://user-images.githubusercontent.com/3740917/155416112-004cbc28-dc1d-4527-8ec3-871e7be51679.png)
4. `Load selected chunks` and observe behaviour: 
![image](https://user-images.githubusercontent.com/3740917/155416326-8ed14e8e-d836-45d7-a6d6-9dfa79821755.png)
5. 
- `Load selected chunks` mixes Chunk loading at Y clip 0<Y<256 and -64<Y<320 (see above).
- Using `Reload chunks` slices the terrain back down to 0<Y<256: 
![image](https://user-images.githubusercontent.com/3740917/155416919-8d031364-f606-48a6-88ad-3ec483eed1e3.png)

---

Alternative steps:

1. Select a 1.18 world with terrain that is above Y 256.
2. Do **NOT** alter `Y min/max clip` (ie leave at 0,256).
3. Select and  `Load selected chunks`.
4. Alter, set `Y min/max clip` to -64,320.
5. `Reload chunks`.
6. Also cry here because you had it working doing it this way before.

---

And when it magically works... (Not actually sure the exact steps to do this and it breaks very easily...) 
![image](https://user-images.githubusercontent.com/3740917/155420684-470d95b8-62f6-4a59-8a7c-18f0d5e7c8a7.png)

---

Additional information - This issue is selection dependant. Below you will see one region vs two chunks without moving the camera. (2.5.0)
![image](https://user-images.githubusercontent.com/3740917/155512017-316118cc-725f-4306-8ab3-0b7ed00dcfb5.png)
![image](https://user-images.githubusercontent.com/3740917/155512028-56d7cd79-d103-4f83-9f02-24e851b46836.png)
(2.4.2)
![image](https://user-images.githubusercontent.com/3740917/155513977-3edd8cc6-03b8-4924-b227-d0bccd16a843.png)

---

2.5.0-15-g1ba5d5b renders Map View correctly:
![image](https://user-images.githubusercontent.com/3740917/155514327-5506e142-6c11-48cc-ad60-8d5c1d81a302.png)

2.5.0-15-g1ba5d5b also correctly renders the chunks:
![image](https://user-images.githubusercontent.com/3740917/155514656-691e851e-6919-454e-a78c-1142b7a81c31.png)

**Comment by Peregrine05** [comment] 2022-02-24 10:13
Does this happen in Stable Snapshot or previous snapshots?

**Comment by jackjt8** [comment] 2022-02-24 11:20
> Does this happen in Stable Snapshot or previous snapshots?

Stable Snapshot. I have only got 2.5.0-15 and 2.5.0-51 to hand.

**Comment by jackjt8** [comment] 2022-03-16 21:01
Unfixed after https://github.com/chunky-dev/chunky/pull/1197 via 2.5.0-SNAPSHOT.75.g8bd28790

![image](https://user-images.githubusercontent.com/3740917/158689560-ca7da7be-26ce-49ca-aadb-19699dfc65de.png)


Should be noted that https://github.com/chunky-dev/chunky/pull/1197 seems to have resolved the selection dependant issues; All chunks are now cut to Y max clip = 256 regardless of whether or not the chunks have data above this and `Y max clip` is set to 320. Map view renders correctly.

**Comment by leMaik** [comment] 2024-09-24 09:43
@jackjt8 This issue is partially caused by the octree overflowing (fixed by #1768) and the chunk data version being incorrect (fixed by #1466). Could you test this against the latest (ie. 611bd42f2d4da0ae3f3d8826a49f311967771100 or later) build of #1466? :pray:

**Comment by NotStirred** [comment] 2024-09-24 10:59
in my testing this world loads fine now, though more testing is always good

**Closed** 2024-09-29 21:12 UTC
Labels: bug, world-loading
