### ISSUE TITLE
Render preview window wont stop expanding.

### ISSUE THREAD

**Issue by NJDaeger** [chunky-dev/chunky#476] opened 2018-03-14 19:47 UTC
When creating a new scene with no chunks selected, the render preview window pops up and won't stop expanding. The reason I don't have any chunks selected is because when I do a large render, I get the coordinates I want to render at, set the camera to that location, then select all the chunks in the camera viewing area, then I load the selected chunks. (This is also where my previous issue comes into play)

**Comment by llbit** [comment] 2018-03-15 15:45
Hm, that's interesting. I've created many empty scenes, and I'm pretty sure I did in the latest version. What OS are you running Chunky on?

**Comment by NJDaeger** [comment] 2018-03-15 19:27
Windows 10.

**Comment by cdeath-zz** [comment] 2018-03-29 15:42
I believe i have a recreation of this issue, windows 10 as well.  Open a map, maximize the window, then move the slider for the divider, it doesn't matter where but you have to move it or the bug doesn't happen.  After this, select any tab in the side window (not just 3d render) then try to move the window, it won't.  If you do this multiple times, it makes the side window take up most of your space and the map is barely visible.  It takes about 3 times to make it take up 75% of your screen space and sometimes even closing and opening again doesn't fix it right away.

This sound like the issue?

**Comment by llbit** [comment] 2018-04-10 22:52
Thanks for the description of how to reproduce. I can't do anything about it now though as I am traveling and don't have access to my Windows 10 machine.

**Comment by llbit** [comment] 2018-04-28 07:42
It seems like you are mentioning two different issues: an expanding render preview window and an issue with the map divider in the main window. I could not reproduce either of the issues. This might have to do with the Java version you are using. I am using Java 8, are you using Java 9?

**Comment by cdeath-zz** [comment] 2018-04-28 16:09
well, somehow i wasn't running the latest version of chunky (which is 1.4.5, I thought when i downloaded it 1.4.4, it would have been the latest version)  so when i updated it, the problem i have no longer happens.  
--------------------
Looking now, the download link still shows 1.4.4.  Also, just updated to newest java 8, and it completely broke the shortcuts for chunky.   I had to reinstall to fix.  Though this time, even though it downloaded 1.4.4, it updated to 1.4.5.  Not sure why it didn't before.

**Closed** 2022-01-16 22:10 UTC
