### ISSUE TITLE
Make farmland a solid block

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1235] opened 2022-04-18 18:08 UTC
Would doing so prevent this from happening? (See image below.)
![image](https://user-images.githubusercontent.com/92183530/163853273-fc52847b-86c1-403b-8842-6f0b22e876dc.png)

**Comment by jackjt8** [comment] 2022-04-18 20:00
Farmland is meant to be less than one block high. We would need a special case to handle this.

**Comment by Peregrine05** [comment] 2022-04-18 20:02
Right now, it is currently rendered in Chunky to be a full block, but it is still not solid. The changing to be a non-full block could probably be done later, but is it easy to make it solid?

**Comment by leMaik** [comment] 2022-04-18 20:06
Duplicate of #888

**Closed by leMaik** 2022-04-18 20:06 UTC

**Comment by Peregrine05** [comment] 2022-04-18 20:08
I was specifically talking about the solidness of the block, not its model.

**Comment by leMaik** [comment] 2022-04-18 20:08
This issue does not describe the bug, unfortunately. The solid property has nothing to do with the block's shape.

**Comment by Peregrine05** [comment] 2022-04-18 20:09
I never meant to describe the block's shape. The bug was that since the block is not solid, water connects to it improperly.

**Comment by leMaik** [comment] 2022-04-18 20:10
"Would doing so prevent this from happening? (See image below.)" is a very bad bug report.

**Comment by Peregrine05** [comment] 2022-04-18 20:10
How should I change it?

**Comment by leMaik** [comment] 2022-04-18 20:14
> Farmland is meant to be less than one block high. We would need a special case to handle this.

@jackjt8 tbh that's a won't fix for me at the moment. This would require to make anything that is on top of farmland to be an entity because otherwise it can't be below its block :thinking:
